introduce flusing
this still doesn't seem to solve the problem that the execution actually
fails, e.g.:

  Error: /Stage[main]/Main/Git_config[merge.tool]: Could not evaluate:
  Execution of 'git config --global merge.tool 'vimdiff3'' returned 1: